---
version: '3.8'
services:
  dockerisego:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE_VERSION=debug
    ports:
      - 8080:8080
    environment:
      APP_STATUS: OK
    healthcheck:
      test: [ "CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/status" ]
      interval: 10s
      timeout: 3s
      retries: 3